apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: roda
data:
  # API Configuration
  API_TITLE: "Mini-Roda Services"
  API_VERSION: "1.0.0"
  
  # Service Ports
  CUSTOMERS_SERVICE_PORT: "8001"
  LOANS_SERVICE_PORT: "8002"
  MFE_CUSTOMERS_PORT: "5173"
  MFE_LOANS_PORT: "5174"
  
  # Gateway Configuration
  GATEWAY_HOST: "localhost"
  GATEWAY_PORT: "80"


