apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: roda

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - customers-service.yaml
  - loans-service.yaml
  - mfe-customers.yaml
  - mfe-loans.yaml
  - traefik-ingressroute.yaml
  - traefik-middleware.yaml

# Images will be updated by GitHub Actions workflow
# This section is managed by kustomize edit set image commands

commonLabels:
  app.kubernetes.io/name: mini-roda
  app.kubernetes.io/part-of: mini-roda
  app.kubernetes.io/managed-by: kustomize
